[training_max]
description = "Uses exercise training max and set tune."
formula = "round(training_max * tune, equipment_rounding)"

[reference]
description = "Uses referenced exercise training max and set tune."
formula = "round(reference_training_max * tune, equipment_rounding)"

[static]
description = "Uses fixed target weight."
formula = "target_weight"
