name = "Intensification"

[[days]]
name = "Day 1"

[[days.exercises]]
exercise = "squat"
sets = [
    { reps = 3, tune = 0.85 },
    { reps = 3, tune = 0.8 },
    { reps = 3, tune = 0.8 },
    { reps = 3, tune = 0.8 },
]

[[days.exercises]]
exercise = "ohp"
sets = [
    { reps = 4, tune = 1.025 },
    { reps = 4, tune = 0.925 },
    { reps = 4, tune = 0.925 },
    { reps = 4, tune = 0.925 },
]

[[days.exercises]]
exercise = "barbell_row"
sets = [{ reps = 6, tune = 1 }, { reps = 6, tune = 1 }, { reps = 6, tune = 1 }]

[[days.exercises]]
exercise = "lateral_raise"
reps = 10
sets = 3

[[days.exercises]]
exercise = "calf_raise"
reps = 12
sets = 3

[[days.exercises]]
exercise = "lying_db_curl"
reps = 12
sets = 3

[[days]]
name = "Day 2"

[[days.exercises]]
exercise = "bench"
sets = [
    { reps = 5, tune = 0.77 },
    { reps = 5, tune = 0.77 },
    { reps = 5, tune = 0.77 },
]

[[days.exercises]]
exercise = "rdl"
sets = [
    { reps = 6, tune = 0.55 },
    { reps = 6, tune = 0.55 },
    { reps = 6, tune = 0.55 },
]

[[days.exercises]]
exercise = "pullups"
reps = 8
sets = 3

[[days.exercises]]
exercise = "db_bench_press"
sets = [{ reps = 8, tune = 0.5 }, { reps = 8, tune = 0.5 }]

[[days.exercises]]
exercise = "wrist_curl"
reps = 12
sets = 3

[[days.exercises]]
exercise = "skullcrusher"
reps = 12
sets = 3

[[days.exercises]]
exercise = "reverse_crunch"
reps = 9
sets = 3
