[plate_milestones]
imperial = [
    { label = "3 plate!", weight = 315 },
    { label = "4 plate!", weight = 405 },
    { label = "5 plate!", weight = 495 },
    { label = "6 plate!", weight = 585 },
    { label = "7 plate!", weight = 675 },
    { label = "8 plate!", weight = 765 },
    { label = "9 plate!", weight = 855 },
    { label = "10 plate!", weight = 945 },
    { label = "11 plate!", weight = 1035 },
]
metric = [
    { label = "3 plate!", weight = 100 },
    { label = "4 plate!", weight = 140 },
    { label = "5 plate!", weight = 180 },
    { label = "6 plate!", weight = 220 },
    { label = "7 plate!", weight = 260 },
    { label = "8 plate!", weight = 300 },
    { label = "9 plate!", weight = 340 },
    { label = "10 plate!", weight = 380 },
    { label = "11 plate!", weight = 420 },
]

[total_milestones]
imperial = [
    1000,
    1100,
    1200,
    1300,
    1400,
    1500,
    1600,
    1700,
    1800,
    1900,
    2000,
    2100,
    2200,
    2300,
    2400,
    2500,
    2600,
    2700,
]
metric = [
    454,
    500,
    545,
    590,
    635,
    680,
    725,
    770,
    815,
    860,
    905,
    950,
    995,
    1040,
    1085,
    1130,
    1175,
    1220,
]
