name = "Intensification"

[[days]]
name = "Day 1"

[[days.exercises]]
exercise = "pullups"
rep_range = [6, 12]
sets = 3

[[days.exercises]]
exercise = "squat"
sets = [
  {reps = 5, tune = 0.75},
  {reps = 5, tune = 0.75},
  {reps = 5, tune = 0.75},
  {reps = 5, tune = 0.75},
]

[[days.exercises]]
exercise = "incline_barbell_bench"
sets = [
  {reps = 5, tune = 0.75},
  {reps = 5, tune = 0.75},
  {reps = 5, tune = 0.75},
  {reps = 5, tune = 0.75},
]

[[days.exercises]]
exercise = "db_row"
rep_range = [8, 12]
sets = 3

[[days.exercises]]
exercise = "lying_db_curl"
rep_range = [10, 12]
sets = 2

[[days.exercises]]
exercise = "calf_raise"
rep_range = [12, 15]
sets = 2

[[days.exercises]]
exercise = "ab_mat_situp"
rep_range = [15, 20]
sets = 2

[[days]]
name = "Day 2"

[[days.exercises]]
exercise = "seated_db_shoulder_press"
rep_range = [8, 12]
sets = 3

[[days.exercises]]
exercise = "barbell_row"
rep_range = [8, 10]
sets = 3

[[days.exercises]]
exercise = "lateral_raise"
rep_range = [12, 15]
sets = 3

[[days.exercises]]
exercise = "bulgarian_split_squat"
rep_range = [8, 10]
sets = 3

[[days.exercises]]
exercise = "preacher_curl"
rep_range = [10, 12]
sets = 2

[[days.exercises]]
exercise = "wrist_curl"
rep_range = [12, 15]
sets = 2

[[days.exercises]]
exercise = "reverse_crunch"
rep_range = [15, 20]
sets = 2

[[days]]
name = "Day 3"

[[days.exercises]]
exercise = "pullups"
rep_range = [6, 12]
sets = 3

[[days.exercises]]
exercise = "bench"
sets = [
  {reps = 3, tune = 0.87},
  {reps = 3, tune = 0.80},
  {reps = 3, tune = 0.80},
  {reps = 3, tune = 0.80},
]

[[days.exercises]]
exercise = "seated_db_shoulder_press"
rep_range = [8, 12]
sets = 3

[[days.exercises]]
exercise = "deadlift"
sets = [
  {reps = 3, tune = 0.80},
  {reps = 3, tune = 0.80},
  {reps = 3, tune = 0.80},
]

[[days.exercises]]
exercise = "skullcrusher"
rep_range = [10, 12]
sets = 2

[[days.exercises]]
exercise = "wrist_extension"
rep_range = [12, 15]
sets = 2

[[days.exercises]]
exercise = "calf_raise"
rep_range = [12, 15]
sets = 2

[[days]]
name = "Day 4"

[[days.exercises]]
exercise = "squat"
sets = [
  {reps = 3, tune = 0.85},
  {reps = 3, tune = 0.80},
  {reps = 3, tune = 0.80},
]

[[days.exercises]]
exercise = "incline_barbell_bench"
sets = [
  {reps = 5, tune = 0.77},
  {reps = 5, tune = 0.77},
  {reps = 5, tune = 0.77},
  {reps = 5, tune = 0.77},
]

[[days.exercises]]
exercise = "rdl"
sets = [
  {reps = 6, tune = 0.55},
  {reps = 6, tune = 0.55},
]

[[days.exercises]]
exercise = "db_row"
rep_range = [8, 12]
sets = 3

[[days.exercises]]
exercise = "lateral_raise"
rep_range = [12, 15]
sets = 2

[[days.exercises]]
exercise = "lying_db_curl"
rep_range = [10, 12]
sets = 2

[[days.exercises]]
exercise = "reverse_crunch"
rep_range = [15, 20]
sets = 2
